### ISSUE TITLE
Upgrading i18n_active-record breaks build

### ISSUE THREAD

**Issue by panterch** [panterch/future_kids#143]
ActiveRecord::Base.logger is unusable because of https://github.com/svenfuchs/i18n-active_record/commit/be0aadaa531de0dd1c22b445823d8c20bb34a4f8

Branch for reproduction of error: https://github.com/panterch/future_kids/tree/issue143

**Comment by panterch** [comment]
Example error:

<pre>
  1) Reminder creation creates a reminder by batch method when criterias met
     Failure/Error: logger.error 'Exception during reminder run'
     
     NoMethodError:
       undefined method `error' for nil:NilClass
     # ./app/models/reminder.rb:73:in `rescue in conditionally_create_reminders'
     # ./app/models/reminder.rb:53:in `conditionally_create_reminders'
     # ./spec/models/reminder_spec.rb:45:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `info' for nil:NilClass
     #   ./app/models/reminder.rb:53:in `conditionally_create_reminders'

Finished in 16.67 seconds (files took 5.97 seconds to load)
289 examples, 1 failure, 1 pending

Failed examples:

rspec ./spec/models/reminder_spec.rb:44 # Reminder creation creates a reminder by batch method when criterias met
</pre>

I think this is caused by https://github.com/svenfuchs/i18n-active_record/blob/be0aadaa531de0dd1c22b445823d8c20bb34a4f8/lib/i18n/backend/active_record/translation.rb#L52
